apiVersion: v1
kind: Service
metadata:
  name: istio-service3
  labels:
    app: istio-service3
spec:
  selector:
    app: istio-service3
  ports:
    - port: 8080
      name: http
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-service3-v1
  labels:
    app: istio-service3
spec:
  selector:
    matchLabels:
      app: istio-service3
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: istio-service3
        version: v1
    spec:
      containers:
        - name: istio-service3
          image: bigpuritz/istio-service3:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
