apiVersion: v1
kind: Service
metadata:
  name: istio-service2
  labels:
    app: istio-service2
spec:
  selector:
    app: istio-service2
  ports:
    - port: 8080
      name: http
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-service2-v1
  labels:
    app: istio-service2
spec:
  selector:
    matchLabels:
      app: istio-service2
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: istio-service2
        version: v1
    spec:
      containers:
        - name: istio-service2
          image: bigpuritz/istio-service2:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
